package nba

var (
	CommonAllPlayer                   = "commonallplayers"
	AllTimeLeadersGrids               = "alltimeleadersgrids"
	AssistLeaders                     = "assistleaders"
	AssistTracker                     = "assisttracker"
	CommonPlayerInfo                  = "commonplayerinfo"
	CommonPlayoffSeries               = "commonplayoffseries"
	CommonTeamRoster                  = "commonteamroster"
	CommonTeamYears                   = "commonteamyears"
	CumulativeStatsPlayer             = "cumestatsplayer"
	CumulativeStatsPlayerGames        = "cumestatsplayergames"
	CumulativeStatsTeam               = "cumestatsteam"
	CumulativeStatsTeamGames          = "cumestatsteamgames"
	DefenseHub                        = "defensehub"
	DraftBoard                        = "draftboard"
	DraftCombineDrillResults          = "draftcombinedrillresults"
	DraftCombineNonStationaryShooting = "draftcombinenonstationaryshooting"
	DraftCombinePlayerAnthro          = "draftcombineplayeranthro"
	DraftCombineSpotShooting          = "draftcombinespotshooting"
	DraftCombineStats                 = "draftcombinestats"
	DraftHistory                      = "drafthistory"
	FranchiseHistory                  = "franchisehistory"
	FranchiseLeaders                  = "franchiseleaders"
	FranchisePlayers                  = "franchiseplayers"
	GameRotation                      = "gamerotation"
)
